import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./stitch-output/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#f58960",
        "tertiary-fixed": "#ffdbcf",
        "on-primary": "#003732",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-container": "#0fbaac",
        "surface-bright": "#31394d",
        "surface-tint": "#4cdbcc",
        secondary: "#b4c5ff",
        "on-tertiary-container": "#6d2301",
        "on-secondary-container": "#cdd7ff",
        surface: "#0b1326",
        "on-surface-variant": "#bbcac6",
        "inverse-on-surface": "#283044",
        "primary-fixed": "#6ef8e8",
        outline: "#859491",
        "on-secondary": "#002a78",
        "on-background": "#dae2fd",
        "on-secondary-fixed": "#00174b",
        "secondary-fixed": "#dbe1ff",
        "secondary-container": "#0053db",
        "on-error": "#690005",
        "inverse-primary": "#006a62",
        error: "#ffb4ab",
        "on-primary-fixed": "#00201d",
        "on-primary-container": "#00443e",
        background: "#0b1326",
        "surface-container-lowest": "#060e20",
        "on-primary-fixed-variant": "#005049",
        "on-secondary-fixed-variant": "#003ea8",
        "on-surface": "#dae2fd",
        "tertiary-fixed-dim": "#ffb59b",
        "on-tertiary-fixed-variant": "#7c2d0b",
        "surface-variant": "#2d3449",
        primary: "#4cdbcc",
        "outline-variant": "#3c4947",
        "surface-container-highest": "#2d3449",
        "on-tertiary": "#5b1b00",
        "on-tertiary-fixed": "#380d00",
        "inverse-surface": "#dae2fd",
        "surface-dim": "#0b1326",
        tertiary: "#ffb59b",
        "surface-container-low": "#131b2e",
        "secondary-fixed-dim": "#b4c5ff",
        "primary-fixed-dim": "#4cdbcc",
        "surface-container": "#171f33",
        "surface-container-high": "#222a3d",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "4px",
        lg: "24px",
        sm: "8px",
        "container-max": "1280px",
        md: "16px",
        xl: "48px",
        "sidebar-collapsed": "72px",
        xs: "4px",
        "sidebar-width": "280px",
      },
      fontSize: {
        "headline-lg": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "label-sm": ["12px", { lineHeight: "14px", fontWeight: "500" }],
        "headline-md": [
          "20px",
          { lineHeight: "28px", fontWeight: "600" },
        ],
        "headline-xl-mobile": [
          "28px",
          { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": [
          "14px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "headline-xl": [
          "36px",
          { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "system-ui", "sans-serif"],
        arabic: ["var(--font-arabic)", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
