export const ErrorCodes = {
  AUTH_EMAIL_PASSWORD_REQUIRED: "AUTH_EMAIL_PASSWORD_REQUIRED",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_SIGNUP_FIELDS_REQUIRED: "AUTH_SIGNUP_FIELDS_REQUIRED",
  AUTH_PASSWORD_TOO_SHORT: "AUTH_PASSWORD_TOO_SHORT",
  AUTH_EMAIL_REGISTERED: "AUTH_EMAIL_REGISTERED",
  AUTH_SIGNUP_NO_YEAR: "AUTH_SIGNUP_NO_YEAR",
  AUTH_EMAIL_EXISTS: "AUTH_EMAIL_EXISTS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  CODE_TOO_MANY_ATTEMPTS: "CODE_TOO_MANY_ATTEMPTS",
  CODE_INVALID: "CODE_INVALID",
  CODE_EXPIRED: "CODE_EXPIRED",
  CODE_LIMIT_REACHED: "CODE_LIMIT_REACHED",
  ACCESS_DENIED: "ACCESS_DENIED",
  MEDIA_NOT_FOUND: "MEDIA_NOT_FOUND",
  NOT_FOUND: "NOT_FOUND",
  LOCALE_INVALID: "LOCALE_INVALID",
  LOCALE_FORBIDDEN: "LOCALE_FORBIDDEN",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
